services:
  server:
    build: apps/OpenSignServer
    container_name: OpenSignServer-dev
    volumes:
      - ./apps/OpenSignServer:/usr/src/app
      - /usr/src/app/node_modules
      - opensign-files:/usr/src/app/files
    ports:
      - "${SERVER_PORT:-8080}:8080"
    depends_on:
      - mongo
    env_file: .env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    command: npx nodemon index.js

  mongo:
    image: mongo:latest
    container_name: mongo-dev
    volumes:
      - data-volume:/data/db
    ports:
      - "${MONGO_PORT:-27017}:27017"
    networks:
      - app-network

  client:
    build: apps/OpenSign
    container_name: OpenSign-dev
    entrypoint: []
    volumes:
      - ./apps/OpenSign:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    depends_on:
      - server
    env_file: .env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    command: npm run dev

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  opensign-files:
