import { useTranslation } from "react-i18next";

const countryCodes = [
  { code: "+93", name: "AF", label: "Afghanistan" },
  { code: "+355", name: "AL", label: "Albania" },
  { code: "+213", name: "DZ", label: "Algeria" },
  { code: "+376", name: "AD", label: "Andorra" },
  { code: "+244", name: "AO", label: "Angola" },
  { code: "+54", name: "AR", label: "Argentina" },
  { code: "+374", name: "AM", label: "Armenia" },
  { code: "+61", name: "AU", label: "Australia" },
  { code: "+43", name: "AT", label: "Austria" },
  { code: "+994", name: "AZ", label: "Azerbaijan" },
  { code: "+973", name: "BH", label: "Bahrain" },
  { code: "+880", name: "BD", label: "Bangladesh" },
  { code: "+375", name: "BY", label: "Belarus" },
  { code: "+32", name: "BE", label: "Belgium" },
  { code: "+501", name: "BZ", label: "Belize" },
  { code: "+229", name: "BJ", label: "Benin" },
  { code: "+975", name: "BT", label: "Bhutan" },
  { code: "+591", name: "BO", label: "Bolivia" },
  { code: "+387", name: "BA", label: "Bosnia & Herzegovina" },
  { code: "+267", name: "BW", label: "Botswana" },
  { code: "+55", name: "BR", label: "Brazil" },
  { code: "+673", name: "BN", label: "Brunei" },
  { code: "+359", name: "BG", label: "Bulgaria" },
  { code: "+226", name: "BF", label: "Burkina Faso" },
  { code: "+257", name: "BI", label: "Burundi" },
  { code: "+855", name: "KH", label: "Cambodia" },
  { code: "+237", name: "CM", label: "Cameroon" },
  { code: "+1", name: "CA", label: "Canada" },
  { code: "+238", name: "CV", label: "Cape Verde" },
  { code: "+236", name: "CF", label: "Central African Republic" },
  { code: "+235", name: "TD", label: "Chad" },
  { code: "+56", name: "CL", label: "Chile" },
  { code: "+86", name: "CN", label: "China" },
  { code: "+57", name: "CO", label: "Colombia" },
  { code: "+269", name: "KM", label: "Comoros" },
  { code: "+242", name: "CG", label: "Congo" },
  { code: "+506", name: "CR", label: "Costa Rica" },
  { code: "+385", name: "HR", label: "Croatia" },
  { code: "+53", name: "CU", label: "Cuba" },
  { code: "+357", name: "CY", label: "Cyprus" },
  { code: "+420", name: "CZ", label: "Czech Republic" },
  { code: "+45", name: "DK", label: "Denmark" },
  { code: "+253", name: "DJ", label: "Djibouti" },
  { code: "+593", name: "EC", label: "Ecuador" },
  { code: "+20", name: "EG", label: "Egypt" },
  { code: "+503", name: "SV", label: "El Salvador" },
  { code: "+240", name: "GQ", label: "Equatorial Guinea" },
  { code: "+372", name: "EE", label: "Estonia" },
  { code: "+251", name: "ET", label: "Ethiopia" },
  { code: "+679", name: "FJ", label: "Fiji" },
  { code: "+358", name: "FI", label: "Finland" },
  { code: "+33", name: "FR", label: "France" },
  { code: "+241", name: "GA", label: "Gabon" },
  { code: "+220", name: "GM", label: "Gambia" },
  { code: "+995", name: "GE", label: "Georgia" },
  { code: "+49", name: "DE", label: "Germany" },
  { code: "+233", name: "GH", label: "Ghana" },
  { code: "+30", name: "GR", label: "Greece" },
  { code: "+590", name: "GP", label: "Guadeloupe" },
  { code: "+224", name: "GN", label: "Guinea" },
  { code: "+245", name: "GW", label: "Guinea-Bissau" },
  { code: "+592", name: "GY", label: "Guyana" },
  { code: "+509", name: "HT", label: "Haiti" },
  { code: "+504", name: "HN", label: "Honduras" },
  { code: "+852", name: "HK", label: "Hong Kong" },
  { code: "+36", name: "HU", label: "Hungary" },
  { code: "+354", name: "IS", label: "Iceland" },
  { code: "+91", name: "IN", label: "India" },
  { code: "+62", name: "ID", label: "Indonesia" },
  { code: "+98", name: "IR", label: "Iran" },
  { code: "+964", name: "IQ", label: "Iraq" },
  { code: "+353", name: "IE", label: "Ireland" },
  { code: "+972", name: "IL", label: "Israel" },
  { code: "+39", name: "IT", label: "Italy" },
  { code: "+225", name: "CI", label: "Ivory Coast" },
  { code: "+81", name: "JP", label: "Japan" },
  { code: "+962", name: "JO", label: "Jordan" },
  { code: "+7", name: "KZ", label: "Kazakhstan" },
  { code: "+254", name: "KE", label: "Kenya" },
  { code: "+383", name: "XK", label: "Kosovo" },
  { code: "+965", name: "KW", label: "Kuwait" },
  { code: "+996", name: "KG", label: "Kyrgyzstan" },
  { code: "+856", name: "LA", label: "Laos" },
  { code: "+371", name: "LV", label: "Latvia" },
  { code: "+961", name: "LB", label: "Lebanon" },
  { code: "+266", name: "LS", label: "Lesotho" },
  { code: "+231", name: "LR", label: "Liberia" },
  { code: "+218", name: "LY", label: "Libya" },
  { code: "+423", name: "LI", label: "Liechtenstein" },
  { code: "+370", name: "LT", label: "Lithuania" },
  { code: "+352", name: "LU", label: "Luxembourg" },
  { code: "+853", name: "MO", label: "Macau" },
  { code: "+261", name: "MG", label: "Madagascar" },
  { code: "+265", name: "MW", label: "Malawi" },
  { code: "+60", name: "MY", label: "Malaysia" },
  { code: "+960", name: "MV", label: "Maldives" },
  { code: "+223", name: "ML", label: "Mali" },
  { code: "+356", name: "MT", label: "Malta" },
  { code: "+596", name: "MQ", label: "Martinique" },
  { code: "+222", name: "MR", label: "Mauritania" },
  { code: "+230", name: "MU", label: "Mauritius" },
  { code: "+262", name: "YT", label: "Mayotte" },
  { code: "+52", name: "MX", label: "Mexico" },
  { code: "+377", name: "MC", label: "Monaco" },
  { code: "+976", name: "MN", label: "Mongolia" },
  { code: "+382", name: "ME", label: "Montenegro" },
  { code: "+212", name: "MA", label: "Morocco" },
  { code: "+258", name: "MZ", label: "Mozambique" },
  { code: "+95", name: "MM", label: "Myanmar" },
  { code: "+264", name: "NA", label: "Namibia" },
  { code: "+977", name: "NP", label: "Nepal" },
  { code: "+31", name: "NL", label: "Netherlands" },
  { code: "+687", name: "NC", label: "New Caledonia" },
  { code: "+64", name: "NZ", label: "New Zealand" },
  { code: "+505", name: "NI", label: "Nicaragua" },
  { code: "+227", name: "NE", label: "Niger" },
  { code: "+234", name: "NG", label: "Nigeria" },
  { code: "+389", name: "MK", label: "North Macedonia" },
  { code: "+47", name: "NO", label: "Norway" },
  { code: "+968", name: "OM", label: "Oman" },
  { code: "+92", name: "PK", label: "Pakistan" },
  { code: "+970", name: "PS", label: "Palestine" },
  { code: "+507", name: "PA", label: "Panama" },
  { code: "+675", name: "PG", label: "Papua New Guinea" },
  { code: "+595", name: "PY", label: "Paraguay" },
  { code: "+51", name: "PE", label: "Peru" },
  { code: "+63", name: "PH", label: "Philippines" },
  { code: "+48", name: "PL", label: "Poland" },
  { code: "+351", name: "PT", label: "Portugal" },
  { code: "+974", name: "QA", label: "Qatar" },
  { code: "+40", name: "RO", label: "Romania" },
  { code: "+7", name: "RU", label: "Russia" },
  { code: "+250", name: "RW", label: "Rwanda" },
  { code: "+290", name: "SH", label: "Saint Helena" },
  { code: "+685", name: "WS", label: "Samoa" },
  { code: "+378", name: "SM", label: "San Marino" },
  { code: "+239", name: "ST", label: "Sao Tome & Principe" },
  { code: "+966", name: "SA", label: "Saudi Arabia" },
  { code: "+221", name: "SN", label: "Senegal" },
  { code: "+381", name: "RS", label: "Serbia" },
  { code: "+248", name: "SC", label: "Seychelles" },
  { code: "+232", name: "SL", label: "Sierra Leone" },
  { code: "+65", name: "SG", label: "Singapore" },
  { code: "+421", name: "SK", label: "Slovakia" },
  { code: "+386", name: "SI", label: "Slovenia" },
  { code: "+677", name: "SB", label: "Solomon Islands" },
  { code: "+252", name: "SO", label: "Somalia" },
  { code: "+27", name: "ZA", label: "South Africa" },
  { code: "+82", name: "KR", label: "South Korea" },
  { code: "+34", name: "ES", label: "Spain" },
  { code: "+94", name: "LK", label: "Sri Lanka" },
  { code: "+249", name: "SD", label: "Sudan" },
  { code: "+597", name: "SR", label: "Suriname" },
  { code: "+268", name: "SZ", label: "Swaziland" },
  { code: "+46", name: "SE", label: "Sweden" },
  { code: "+41", name: "CH", label: "Switzerland" },
  { code: "+963", name: "SY", label: "Syria" },
  { code: "+886", name: "TW", label: "Taiwan" },
  { code: "+992", name: "TJ", label: "Tajikistan" },
  { code: "+255", name: "TZ", label: "Tanzania" },
  { code: "+66", name: "TH", label: "Thailand" },
  { code: "+228", name: "TG", label: "Togo" },
  { code: "+676", name: "TO", label: "Tonga" },
  { code: "+216", name: "TN", label: "Tunisia" },
  { code: "+90", name: "TR", label: "Turkey" },
  { code: "+993", name: "TM", label: "Turkmenistan" },
  { code: "+256", name: "UG", label: "Uganda" },
  { code: "+380", name: "UA", label: "Ukraine" },
  { code: "+971", name: "AE", label: "United Arab Emirates" },
  { code: "+44", name: "GB", label: "United Kingdom" },
  { code: "+1", name: "US", label: "United States" },
  { code: "+598", name: "UY", label: "Uruguay" },
  { code: "+998", name: "UZ", label: "Uzbekistan" },
  { code: "+678", name: "VU", label: "Vanuatu" },
  { code: "+379", name: "VA", label: "Vatican City" },
  { code: "+58", name: "VE", label: "Venezuela" },
  { code: "+84", name: "VN", label: "Vietnam" },
  { code: "+681", name: "WF", label: "Wallis and Futuna" },
  { code: "+967", name: "YE", label: "Yemen" },
  { code: "+260", name: "ZM", label: "Zambia" },
  { code: "+263", name: "ZW", label: "Zimbabwe" },
];

function CountryCodeSelect({ value, onChange }) {
  const { t } = useTranslation();

  return (
    <select
      className="op-select op-select-bordered op-select-sm focus:outline-none hover:border-base-content text-xs"
      value={value}
      onChange={(e) => onChange(e.target.value)}
    >
      <option value="">{t("country-code")}</option>
      {countryCodes.map((c) => (
        <option key={c.code + c.name} value={c.code}>
          {c.name} {c.code}
        </option>
      ))}
    </select>
  );
}

export function hasValidCountryCode(phone) {
  if (!phone || typeof phone !== "string") return false;
  if (!phone.startsWith("+")) return false;
  for (const c of countryCodes) {
    if (phone.startsWith(c.code)) return true;
  }
  return false;
}

export default CountryCodeSelect;
